name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # or master, depending on your default branch
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0.x'  # Use your .NET version

    - name: Run Blog Post Processor
      run: |
        if ! dotnet run --project BlogPostProcessor/BlogPostProcessor.csproj; then
          echo "Blog post processing failed"
          exit 1
        fi
        
    - name: Publish .NET Core Project
      run: dotnet publish BlogWebAssembly.sln -c Release -o release --nologo
    
    # Change this part - Move files from the subdirectory to wwwroot
    - name: Move files to correct location
      run: |
        mv release/wwwroot/blog/* release/wwwroot/
        rm -rf release/wwwroot/blog
      
    # Add .nojekyll file to tell GitHub pages not to run through Jekyll
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        branch: github-pages    # The branch the action should deploy to
        folder: release/wwwroot    # The folder the action should deploy
        clean: true    # Automatically remove deleted files from the deployment branch
